# Analysis of Splicing Predictions on Assays

1. Liao et al. 2023: synthetic sequence splicing assay
2. Baeza-Centurion et al. 2025: *FAS* exon 6 mutagenesis assay
3. Chong et al. 2019: MFASS assay

## 1. Setup and Imports

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
import scipy.stats
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf

# Custom utility modules
import sequence_utils as seq_utils
import plotting_utils as plot_utils
import modeling_utils as model_utils

## 2. Data Loading

In [2]:
csv_paths = {
    "liao2023": "../data/Liao_2023_SplicingPredictions.csv.gz",
    "baeza-centurion2025": "../data/Baeza_Centurion_2025_SplicingPredictions.csv.gz",
    "chong2019": "../data/Chong_2019_SplicingPredictions.csv.gz",
}

display_names = {
    "liao2023": "Liao et al. 2023",
    "baeza-centurion2025": "FAS Exon 6",
    "chong2019": "MFASS",
}

assay_data = dict()
for key, path in csv_paths.items():
    assay_data[key] = pd.read_csv(path)

assay_data["liao2023"]["PSI"] = assay_data["liao2023"]["PSI"] * 100

assay_data["baeza-centurion2025"]["exon"] = assay_data["baeza-centurion2025"]["sequence"]
assay_data["baeza-centurion2025"]["PSI"] = assay_data["baeza-centurion2025"]["psi"]

# Filter MFASS only to WT and exonic variant sequences
assay_data["chong2019"] = assay_data["chong2019"].loc[(
    (assay_data["chong2019"]["label"] == "exon") |
    (assay_data["chong2019"]["category"] == "natural")
)]
assay_data["chong2019"]["PSI"] = assay_data["chong2019"]["v2_index"] * 100

## 3. Splicing Predictions

In [3]:
# Add average Pangolin tissue usage score
for key, data in assay_data.items():
    assay_data[key]["pangolin_average_usage_avg"] = (
        assay_data[key]["pangolin_heart_usage_avg"] +
        assay_data[key]["pangolin_liver_usage_avg"] +
        assay_data[key]["pangolin_brain_usage_avg"] +
        assay_data[key]["pangolin_testis_usage_avg"]
    ) / 4

In [4]:
assay_data["liao2023"][[
    "PSI", "spliceai_avg", "alphagenome_junctions_psi", 
    "pangolin_average_usage_avg",
]].corr()

,PSI,spliceai_avg,alphagenome_junctions_psi,pangolin_average_usage_avg
PSI,1.000000,0.846221,0.840621,0.780118
spliceai_avg,0.846221,1.000000,0.905043,0.933030
alphagenome_junctions_psi,0.840621,0.905043,1.000000,0.800085
pangolin_average_usage_avg,0.780118,0.933030,0.800085,1.000000

In [5]:
assay_data["baeza-centurion2025"][[
    "PSI", "spliceai_avg", "alphagenome_junctions_psi", 
    "pangolin_average_usage_avg",
]].corr()

,PSI,spliceai_avg,alphagenome_junctions_psi,pangolin_average_usage_avg
PSI,1.000000,0.830704,0.836509,0.752624
spliceai_avg,0.830704,1.000000,0.944121,0.785024
alphagenome_junctions_psi,0.836509,0.944121,1.000000,0.713120
pangolin_average_usage_avg,0.752624,0.785024,0.713120,1.000000

In [6]:
assay_data["chong2019"][[
    "PSI", "spliceai_avg", "alphagenome_junctions_psi", 
    "pangolin_average_usage_avg",
]].corr()

,PSI,spliceai_avg,alphagenome_junctions_psi,pangolin_average_usage_avg
PSI,1.000000,0.395731,0.452931,0.397659
spliceai_avg,0.395731,1.000000,0.792124,0.799672
alphagenome_junctions_psi,0.452931,0.792124,1.000000,0.804052
pangolin_average_usage_avg,0.397659,0.799672,0.804052,1.000000

## 4. Add CpG and stop codon metadata

In [7]:
for key, data in assay_data.items():
    assay_data[key] = seq_utils.add_CpG_features(assay_data[key], sequence_col="exon")
    assay_data[key] = seq_utils.add_stop_codon_features(assay_data[key], sequence_col="exon")

In [8]:
# Discretize CpG and GpC obs/exp ratios
for key, data in assay_data.items():
    for dinuc in ["CpG", "GpC"]:    
        assay_data[key][f"{dinuc}_obs_exp_disc"] = plot_utils.discretize_variable(
            assay_data[key][f"{dinuc}_obs_exp"], 
            0.25,
            min_val=None, 
            max_val=1.75,
            labels=True,
            include_above_max=True,
        )
        assay_data[key][f"{dinuc}_obs_exp_disc"] = plot_utils.discretize_variable(
            assay_data[key][f"{dinuc}_obs_exp"], 
            0.25,
            min_val=None, 
            max_val=1.75,
            labels=True,
            include_above_max=True,
        )

In [9]:
for key, data in assay_data.items():
    print(key, len(data))

liao2023 239772
baeza-centurion2025 5976
chong2019 16469

## 5. Add model errors

In [10]:
for key, data in assay_data.items():
    assay_data[key]["spliceai_avg_error"] = assay_data[key]["spliceai_avg"] * 100 - assay_data[key]["PSI"]
    assay_data[key]["alphagenome_junctions_psi_error"] = assay_data[key]["alphagenome_junctions_psi"] * 100 - assay_data[key]["PSI"]
    assay_data[key]["pangolin_average_usage_avg_error"] = assay_data[key]["pangolin_average_usage_avg"] * 100 - assay_data[key]["PSI"]

In [11]:
model_error_cols = {
    "spliceai_avg_error": "SpliceAI",
    "pangolin_average_usage_avg_error": "Pangolin",
    "alphagenome_junctions_psi_error": "AlphaGenome"
}

## 6. CpG Bias

In [21]:
bbox_to_anchors = {
    "liao2023" : (0.5, -0.55),
    "baeza-centurion2025": (0.5, -0.50),
    "chong2019": (0.5, -0.62),
}

ceiling_counts = {
    "liao2023" : 8,
    "baeza-centurion2025": 10,
    "chong2019": 8,
}

target_bins = {
    "liao2023" : 5,
    "baeza-centurion2025": 5,
    "chong2019": 10,
}

figsizes = {
    "liao2023" : (5.8, 3.25),
    "baeza-centurion2025": (5.8, 3.25),
    "chong2019": (5.8, 3.25),
}

In [22]:
group_col = {
    "liao2023" : "CpG_obs_exp_disc",
    "baeza-centurion2025": "CpG_obs",
    "chong2019": "CpG_obs_exp_disc",
}

group_continuous_col = {
    "liao2023" : "CpG_obs_exp",
    "baeza-centurion2025": "CpG_obs",
    "chong2019": "CpG_obs_exp",
}

group_label = {
    "liao2023" : "CpG Ratio",
    "baeza-centurion2025": "Number of CpG",
    "chong2019": "CpG Ratio",
}

for key, data in assay_data.items():
    for model_col, model_name in model_error_cols.items():
        fig = plot_utils.plot_grouped_violin_analysis(
            data,
            predictor_col=model_col,
            target_col="PSI",
            group_col=group_col[key],
            predictor_label=f"Model Error (Score - PSI)",
            target_label="Experimentally Measured PSI",
            group_label=group_label[key],
            target_bins=target_bins[key],
            ceiling_count=ceiling_counts[key],
            min_samples=20,
            title=f"{display_names[key]}, {model_name}",
            cmap='inferno',
            ylim=(-105, 105),
            legend=True,
            legend_loc="lower center",
            legend_ncols=8,
            bbox_to_anchor=bbox_to_anchors[key],
            dpi=600,
            figsize=figsizes[key],
            fontsize_title=10,
            fontsize_axis_labels=10,
            fontsize_xtick=10,
            fontsize_ytick=10,
            fontsize_legend=10,
            fontsize_sample_counts=5,
            numeric_binning=False,
            legend_row_major=True
        )
        fig.show()
        fig.savefig(f"figures/{key}_{model_col}_CpG_Error.svg", bbox_inches='tight')
        plt.close()
                
        model = smf.ols(f"{model_col} ~ {group_continuous_col[key]} + PSI", data=data).fit()
        print(key, model_name, model.summary())

liao2023 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.462
Model:                            OLS   Adj. R-squared:                  0.462
Method:                 Least Squares   F-statistic:                 1.030e+05
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:23:48   Log-Likelihood:            -1.0174e+06
No. Observations:              239772   AIC:                         2.035e+06
Df Residuals:                  239769   BIC:                         2.035e+06
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       9.5259      0.099     96.606      0.000       9.333       9.719
CpG_obs_exp    11.9897      0.086    139.289      0.000      11.821      12.158
PSI            -0.3698      0.001   -450.437      0.000      -0.371      -0.368
==============================================================================
Omnibus:                     7757.866   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            16582.519
Skew:                           0.209   Prob(JB):                         0.00
Kurtosis:                       4.219   Cond. No.                         268.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.761
Model:                                          OLS   Adj. R-squared:                  0.761
Method:                               Least Squares   F-statistic:                 3.826e+05
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:23:49   Log-Likelihood:            -9.7300e+05
No. Observations:                            239772   AIC:                         1.946e+06
Df Residuals:                                239769   BIC:                         1.946e+06
Df Model:                                         2
Covariance Type:                          nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      -2.0978      0.082    -25.603      0.000      -2.258      -1.937
CpG_obs_exp     7.4534      0.072    104.205      0.000       7.313       7.594
PSI            -0.5953      0.001   -872.524      0.000      -0.597      -0.594
==============================================================================
Omnibus:                       80.497   Durbin-Watson:                   2.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               87.064
Skew:                          -0.013   Prob(JB):                     1.24e-19
Kurtosis:                       3.090   Cond. No.                         268.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.264
Model:                                         OLS   Adj. R-squared:                  0.264
Method:                              Least Squares   F-statistic:                 4.303e+04
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:23:51   Log-Likelihood:            -1.0569e+06
No. Observations:                           239772   AIC:                         2.114e+06
Df Residuals:                               239769   BIC:                         2.114e+06
Df Model:                                        2
Covariance Type:                         nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      20.0237      0.116    172.241      0.000      19.796      20.252
CpG_obs_exp     8.6759      0.101     85.489      0.000       8.477       8.875
PSI            -0.2824      0.001   -291.722      0.000      -0.284      -0.280
==============================================================================
Omnibus:                    34410.786   Durbin-Watson:                   1.997
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            68958.060
Skew:                           0.891   Prob(JB):                         0.00
Kurtosis:                       4.930   Cond. No.                         268.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
baeza-centurion2025 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.531
Model:                            OLS   Adj. R-squared:                  0.530
Method:                 Least Squares   F-statistic:                     3375.
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:23:51   Log-Likelihood:                -23399.
No. Observations:                5976   AIC:                         4.680e+04
Df Residuals:                    5973   BIC:                         4.683e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     33.1778      0.282    117.800      0.000      32.626      33.730
CpG_obs        2.3680      0.422      5.609      0.000       1.540       3.196
PSI           -0.4275      0.006    -77.168      0.000      -0.438      -0.417
==============================================================================
Omnibus:                      357.894   Durbin-Watson:                   1.407
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              770.847
Skew:                          -0.398   Prob(JB):                    4.10e-168
Kurtosis:                       4.569   Cond. No.                         149.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
baeza-centurion2025 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.938
Model:                                          OLS   Adj. R-squared:                  0.938
Method:                               Least Squares   F-statistic:                 4.485e+04
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:23:51   Log-Likelihood:                -19341.
No. Observations:                              5976   AIC:                         3.869e+04
Df Residuals:                                  5973   BIC:                         3.871e+04
Df Model:                                         2
Covariance Type:                          nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.3248      0.143      2.274      0.023       0.045       0.605
CpG_obs        3.9230      0.214     18.328      0.000       3.503       4.343
PSI           -0.7880      0.003   -280.540      0.000      -0.793      -0.782
==============================================================================
Omnibus:                      955.237   Durbin-Watson:                   1.345
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1888.410
Skew:                           0.977   Prob(JB):                         0.00
Kurtosis:                       4.940   Cond. No.                         149.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
baeza-centurion2025 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.238
Model:                                         OLS   Adj. R-squared:                  0.237
Method:                              Least Squares   F-statistic:                     930.9
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:23:51   Log-Likelihood:                -24619.
No. Observations:                             5976   AIC:                         4.924e+04
Df Residuals:                                 5973   BIC:                         4.926e+04
Df Model:                                        2
Covariance Type:                         nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     31.5972      0.345     91.476      0.000      30.920      32.274
CpG_obs        1.5312      0.518      2.958      0.003       0.516       2.546
PSI           -0.2753      0.007    -40.529      0.000      -0.289      -0.262
==============================================================================
Omnibus:                      130.229   Durbin-Watson:                   1.584
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              207.140
Skew:                          -0.212   Prob(JB):                     1.05e-45
Kurtosis:                       3.807   Cond. No.                         149.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
chong2019 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.788
Model:                            OLS   Adj. R-squared:                  0.788
Method:                 Least Squares   F-statistic:                 3.065e+04
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:23:51   Log-Likelihood:                -55865.
No. Observations:               16469   AIC:                         1.117e+05
Df Residuals:                   16466   BIC:                         1.118e+05
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      78.5159      0.320    245.436      0.000      77.889      79.143
CpG_obs_exp     1.8236      0.200      9.116      0.000       1.431       2.216
PSI            -0.8187      0.003   -247.532      0.000      -0.825      -0.812
==============================================================================
Omnibus:                    13735.085   Durbin-Watson:                   0.675
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           425558.822
Skew:                          -3.911   Prob(JB):                         0.00
Kurtosis:                      26.643   Cond. No.                         548.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
chong2019 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.526
Model:                                          OLS   Adj. R-squared:                  0.526
Method:                               Least Squares   F-statistic:                     9121.
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:23:52   Log-Likelihood:                -63514.
No. Observations:                             16469   AIC:                         1.270e+05
Df Residuals:                                 16466   BIC:                         1.271e+05
Df Model:                                         2
Covariance Type:                          nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      35.2860      0.509     69.325      0.000      34.288      36.284
CpG_obs_exp     4.0561      0.318     12.743      0.000       3.432       4.680
PSI            -0.7103      0.005   -134.975      0.000      -0.721      -0.700
==============================================================================
Omnibus:                     5682.408   Durbin-Watson:                   0.587
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            21878.289
Skew:                          -1.701   Prob(JB):                         0.00
Kurtosis:                       7.507   Cond. No.                         548.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
chong2019 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.328
Model:                                         OLS   Adj. R-squared:                  0.328
Method:                              Least Squares   F-statistic:                     4015.
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:23:52   Log-Likelihood:                -67017.
No. Observations:                            16469   AIC:                         1.340e+05
Df Residuals:                                16466   BIC:                         1.341e+05
Df Model:                                        2
Covariance Type:                         nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      49.9420      0.630     79.321      0.000      48.708      51.176
CpG_obs_exp     6.2469      0.394     15.866      0.000       5.475       7.019
PSI            -0.5792      0.007    -88.973      0.000      -0.592      -0.566
==============================================================================
Omnibus:                     9963.725   Durbin-Watson:                   0.694
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           110648.509
Skew:                          -2.774   Prob(JB):                         0.00
Kurtosis:                      14.422   Cond. No.                         548.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

### GpC Control

In [23]:
group_col = {
    "liao2023" : "GpC_obs_exp_disc",
    "baeza-centurion2025": "GpC_obs",
    "chong2019": "GpC_obs_exp_disc",
}

group_continuous_col = {
    "liao2023" : "GpC_obs_exp",
    "baeza-centurion2025": "GpC_obs",
    "chong2019": "GpC_obs_exp",
}

group_label = {
    "liao2023" : "GpC Ratio",
    "baeza-centurion2025": "Number of GpC",
    "chong2019": "GpC Ratio",
}

for key, data in assay_data.items():
    for model_col, model_name in model_error_cols.items():
        fig = plot_utils.plot_grouped_violin_analysis(
            data,
            predictor_col=model_col,
            target_col="PSI",
            group_col=group_col[key],
            predictor_label=f"Model Error (Score - PSI)",
            target_label="Experimentally Measured PSI",
            group_label=group_label[key],
            target_bins=target_bins[key],
            ceiling_count=ceiling_counts[key],
            min_samples=20,
            title=f"{display_names[key]}, {model_name}",
            cmap='inferno',
            ylim=(-105, 105),
            legend=True,
            legend_loc="lower center",
            legend_ncols=8,
            bbox_to_anchor=bbox_to_anchors[key],
            dpi=600,
            figsize=figsizes[key],
            fontsize_title=10,
            fontsize_axis_labels=10,
            fontsize_xtick=10,
            fontsize_ytick=10,
            fontsize_legend=10,
            fontsize_sample_counts=5,
            numeric_binning=(key == "baeza-centurion2025"),
            numeric_bin_size=1,
            legend_row_major=True
        )
        fig.show()
        fig.savefig(f"figures/{key}_{model_col}_GpC_Error.svg", bbox_inches='tight')
        plt.close()

        model = smf.ols(f"{model_col} ~ {group_continuous_col[key]} + PSI", data=data).fit()
        print(key, model_name, model.summary())

liao2023 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.419
Model:                            OLS   Adj. R-squared:                  0.419
Method:                 Least Squares   F-statistic:                 8.640e+04
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:23:53   Log-Likelihood:            -1.0267e+06
No. Observations:              239772   AIC:                         2.053e+06
Df Residuals:                  239769   BIC:                         2.053e+06
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      21.5632      0.113    190.531      0.000      21.341      21.785
GpC_obs_exp    -1.0453      0.088    -11.884      0.000      -1.218      -0.873
PSI            -0.3489      0.001   -415.304      0.000      -0.351      -0.347
==============================================================================
Omnibus:                     7282.814   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            16039.613
Skew:                           0.178   Prob(JB):                         0.00
Kurtosis:                       4.216   Cond. No.                         286.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.751
Model:                                          OLS   Adj. R-squared:                  0.751
Method:                               Least Squares   F-statistic:                 3.611e+05
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:23:55   Log-Likelihood:            -9.7824e+05
No. Observations:                            239772   AIC:                         1.956e+06
Df Residuals:                                239769   BIC:                         1.957e+06
Df Model:                                         2
Covariance Type:                          nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       5.5605      0.092     60.126      0.000       5.379       5.742
GpC_obs_exp    -0.8130      0.072    -11.311      0.000      -0.954      -0.672
PSI            -0.5824      0.001   -848.330      0.000      -0.584      -0.581
==============================================================================
Omnibus:                      109.951   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              120.916
Skew:                          -0.013   Prob(JB):                     5.54e-27
Kurtosis:                       3.107   Cond. No.                         286.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.242
Model:                                         OLS   Adj. R-squared:                  0.242
Method:                              Least Squares   F-statistic:                 3.822e+04
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:23:57   Log-Likelihood:            -1.0605e+06
No. Observations:                           239772   AIC:                         2.121e+06
Df Residuals:                               239769   BIC:                         2.121e+06
Df Model:                                        2
Covariance Type:                         nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      28.4682      0.130    218.463      0.000      28.213      28.724
GpC_obs_exp    -0.5092      0.101     -5.027      0.000      -0.708      -0.311
PSI            -0.2671      0.001   -276.096      0.000      -0.269      -0.265
==============================================================================
Omnibus:                    34772.099   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            70642.332
Skew:                           0.894   Prob(JB):                         0.00
Kurtosis:                       4.968   Cond. No.                         286.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
baeza-centurion2025 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.575
Model:                            OLS   Adj. R-squared:                  0.575
Method:                 Least Squares   F-statistic:                     4049.
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:23:57   Log-Likelihood:                -23099.
No. Observations:                5976   AIC:                         4.620e+04
Df Residuals:                    5973   BIC:                         4.622e+04
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     24.5563      0.424     57.943      0.000      23.726      25.387
GpC_obs        5.9937      0.232     25.826      0.000       5.539       6.449
PSI           -0.4807      0.005    -88.264      0.000      -0.491      -0.470
==============================================================================
Omnibus:                      211.465   Durbin-Watson:                   1.344
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              491.493
Skew:                          -0.194   Prob(JB):                    1.88e-107
Kurtosis:                       4.351   Cond. No.                         173.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
baeza-centurion2025 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.934
Model:                                          OLS   Adj. R-squared:                  0.934
Method:                               Least Squares   F-statistic:                 4.231e+04
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:23:57   Log-Likelihood:                -19504.
No. Observations:                              5976   AIC:                         3.901e+04
Df Residuals:                                  5973   BIC:                         3.903e+04
Df Model:                                         2
Covariance Type:                          nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.3059      0.232      1.317      0.188      -0.149       0.761
GpC_obs       -0.1296      0.127     -1.019      0.308      -0.379       0.120
PSI           -0.7656      0.003   -256.584      0.000      -0.771      -0.760
==============================================================================
Omnibus:                      950.437   Durbin-Watson:                   1.342
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1936.986
Skew:                           0.961   Prob(JB):                         0.00
Kurtosis:                       5.022   Cond. No.                         173.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
baeza-centurion2025 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.408
Model:                                         OLS   Adj. R-squared:                  0.408
Method:                              Least Squares   F-statistic:                     2059.
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:23:57   Log-Likelihood:                -23863.
No. Observations:                             5976   AIC:                         4.773e+04
Df Residuals:                                 5973   BIC:                         4.775e+04
Df Model:                                        2
Covariance Type:                         nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     15.9562      0.482     33.132      0.000      15.012      16.900
GpC_obs       10.9744      0.264     41.611      0.000      10.457      11.491
PSI           -0.3877      0.006    -62.647      0.000      -0.400      -0.376
==============================================================================
Omnibus:                      141.046   Durbin-Watson:                   1.454
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              324.416
Skew:                          -0.034   Prob(JB):                     3.58e-71
Kurtosis:                       4.139   Cond. No.                         173.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
chong2019 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.787
Model:                            OLS   Adj. R-squared:                  0.787
Method:                 Least Squares   F-statistic:                 3.047e+04
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:23:57   Log-Likelihood:                -55904.
No. Observations:               16469   AIC:                         1.118e+05
Df Residuals:                   16466   BIC:                         1.118e+05
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      79.4339      0.343    231.731      0.000      78.762      80.106
GpC_obs_exp    -0.3422      0.147     -2.333      0.020      -0.630      -0.055
PSI            -0.8169      0.003   -246.830      0.000      -0.823      -0.810
==============================================================================
Omnibus:                    13639.723   Durbin-Watson:                   0.677
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           410636.156
Skew:                          -3.880   Prob(JB):                         0.00
Kurtosis:                      26.199   Cond. No.                         589.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
chong2019 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.521
Model:                                          OLS   Adj. R-squared:                  0.521
Method:                               Least Squares   F-statistic:                     8962.
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:23:57   Log-Likelihood:                -63590.
No. Observations:                             16469   AIC:                         1.272e+05
Df Residuals:                                 16466   BIC:                         1.272e+05
Df Model:                                         2
Covariance Type:                          nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      35.9088      0.547     65.692      0.000      34.837      36.980
GpC_obs_exp     0.7500      0.234      3.206      0.001       0.291       1.209
PSI            -0.7065      0.005   -133.855      0.000      -0.717      -0.696
==============================================================================
Omnibus:                     5745.332   Durbin-Watson:                   0.590
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            22348.461
Skew:                          -1.718   Prob(JB):                         0.00
Kurtosis:                       7.557   Cond. No.                         589.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
chong2019 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.318
Model:                                         OLS   Adj. R-squared:                  0.318
Method:                              Least Squares   F-statistic:                     3847.
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:23:58   Log-Likelihood:                -67130.
No. Observations:                            16469   AIC:                         1.343e+05
Df Residuals:                                16466   BIC:                         1.343e+05
Df Model:                                        2
Covariance Type:                         nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      53.2965      0.678     78.641      0.000      51.968      54.625
GpC_obs_exp    -1.3955      0.290     -4.811      0.000      -1.964      -0.827
PSI            -0.5730      0.007    -87.565      0.000      -0.586      -0.560
==============================================================================
Omnibus:                     9932.543   Durbin-Watson:                   0.698
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           108416.713
Skew:                          -2.770   Prob(JB):                         0.00
Kurtosis:                      14.283   Cond. No.                         589.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## 7. Stop Codon Bias

In [24]:
bbox_to_anchors = {
    "liao2023" : (0.5, -0.55),
}
ceiling_counts = {
    "liao2023" : 8,
}
target_bins = {
    "liao2023" : 5,
}
figsizes = {
    "liao2023" : (3.75, 2.5),#(2.8, 2.25),
}

stop_codon_cols = [
    ("Number of TAA", "TAA", "TAA_count"), 
    ("Number of TAG", "TAG", "TAG_count"),
    ("Number of TGA", "TGA", "TGA_count"),
    ("Number of Stop Codons", "Stop Codon", "stop_codon_count"),
]

for model_col, model_name in model_error_cols.items():
    for col_name, col_title, stop_codon_col in stop_codon_cols:
        fig = plot_utils.plot_grouped_violin_analysis(
            assay_data["liao2023"], 
            predictor_col=model_col,
            target_col="PSI", 
            group_col=stop_codon_col,
            group_label=col_name,
            predictor_label=f"Model Error (Score - PSI)",
            target_label="Experimentally Measured PSI",
            target_bins=target_bins["liao2023"],
            ceiling_count=ceiling_counts["liao2023"],
            title=f"Liao et al. 2023, {model_name} ({col_title})",
            cmap='inferno',
            ylim=(-105, 105),
            legend_loc="lower center",
            legend_ncols=5,
            bbox_to_anchor=bbox_to_anchors["liao2023"],
            dpi=600,
            figsize=figsizes["liao2023"],
            fontsize_title=10,
            fontsize_axis_labels=10,
            fontsize_ytick=10,
            fontsize_legend=10,
            fontsize_sample_counts=6.5,
            min_samples=20,
            numeric_binning=True,
            legend_row_major=True
        )
        fig.savefig(f"figures/liao2023_{model_col}_{stop_codon_col}_StopCodon_Error.svg", bbox_inches='tight')
        plt.close()

        model = smf.ols(f"{model_col} ~ {stop_codon_col} + PSI", data=assay_data["liao2023"]).fit()
        print("liao2023", model_name, model.summary())

liao2023 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.438
Model:                            OLS   Adj. R-squared:                  0.438
Method:                 Least Squares   F-statistic:                 9.354e+04
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:24:00   Log-Likelihood:            -1.0226e+06
No. Observations:              239772   AIC:                         2.045e+06
Df Residuals:                  239769   BIC:                         2.045e+06
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     25.8920      0.085    303.843      0.000      25.725      26.059
TAA_count     -3.1290      0.034    -91.902      0.000      -3.196      -3.062
PSI           -0.3747      0.001   -429.242      0.000      -0.376      -0.373
==============================================================================
Omnibus:                     6668.307   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14862.526
Skew:                           0.146   Prob(JB):                         0.00
Kurtosis:                       4.184   Cond. No.                         187.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.441
Model:                            OLS   Adj. R-squared:                  0.441
Method:                 Least Squares   F-statistic:                 9.465e+04
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:24:03   Log-Likelihood:            -1.0220e+06
No. Observations:              239772   AIC:                         2.044e+06
Df Residuals:                  239769   BIC:                         2.044e+06
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     25.0711      0.077    325.716      0.000      24.920      25.222
TAG_count     -4.2658      0.043    -98.690      0.000      -4.351      -4.181
PSI           -0.3725      0.001   -434.254      0.000      -0.374      -0.371
==============================================================================
Omnibus:                     6949.674   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            15638.660
Skew:                           0.154   Prob(JB):                         0.00
Kurtosis:                       4.213   Cond. No.                         174.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.420
Model:                            OLS   Adj. R-squared:                  0.420
Method:                 Least Squares   F-statistic:                 8.698e+04
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:24:06   Log-Likelihood:            -1.0263e+06
No. Observations:              239772   AIC:                         2.053e+06
Df Residuals:                  239769   BIC:                         2.053e+06
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     21.2796      0.069    309.644      0.000      21.145      21.414
TGA_count     -1.1702      0.041    -28.601      0.000      -1.250      -1.090
PSI           -0.3465      0.001   -413.147      0.000      -0.348      -0.345
==============================================================================
Omnibus:                     7378.032   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            16165.185
Skew:                           0.184   Prob(JB):                         0.00
Kurtosis:                       4.218   Cond. No.                         149.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.463
Model:                            OLS   Adj. R-squared:                  0.463
Method:                 Least Squares   F-statistic:                 1.033e+05
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:24:08   Log-Likelihood:            -1.0172e+06
No. Observations:              239772   AIC:                         2.034e+06
Df Residuals:                  239769   BIC:                         2.034e+06
Df Model:                           2
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           32.2225      0.103    312.993      0.000      32.021      32.424
stop_codon_count    -3.3229      0.024   -140.629      0.000      -3.369      -3.277
PSI                 -0.3906      0.001   -454.060      0.000      -0.392      -0.389
==============================================================================
Omnibus:                     6780.597   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            15108.389
Skew:                           0.151   Prob(JB):                         0.00
Kurtosis:                       4.192   Cond. No.                         226.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.760
Model:                                          OLS   Adj. R-squared:                  0.760
Method:                               Least Squares   F-statistic:                 3.801e+05
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:24:11   Log-Likelihood:            -9.7358e+05
No. Observations:                            239772   AIC:                         1.947e+06
Df Residuals:                                239769   BIC:                         1.947e+06
Df Model:                                         2
Covariance Type:                          nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      9.4340      0.069    135.808      0.000       9.298       9.570
TAA_count     -2.7243      0.028    -98.159      0.000      -2.779      -2.670
PSI           -0.6049      0.001   -850.015      0.000      -0.606      -0.604
==============================================================================
Omnibus:                      110.916   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              116.107
Skew:                          -0.035   Prob(JB):                     6.13e-26
Kurtosis:                       3.083   Cond. No.                         187.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.761
Model:                                          OLS   Adj. R-squared:                  0.761
Method:                               Least Squares   F-statistic:                 3.817e+05
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:24:13   Log-Likelihood:            -9.7322e+05
No. Observations:                            239772   AIC:                         1.946e+06
Df Residuals:                                239769   BIC:                         1.946e+06
Df Model:                                         2
Covariance Type:                          nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.5927      0.063    136.797      0.000       8.470       8.716
TAG_count     -3.5976      0.035   -101.991      0.000      -3.667      -3.528
PSI           -0.6023      0.001   -860.502      0.000      -0.604      -0.601
==============================================================================
Omnibus:                       81.852   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               85.556
Skew:                          -0.028   Prob(JB):                     2.64e-19
Kurtosis:                       3.074   Cond. No.                         174.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.753
Model:                                          OLS   Adj. R-squared:                  0.753
Method:                               Least Squares   F-statistic:                 3.652e+05
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:24:16   Log-Likelihood:            -9.7721e+05
No. Observations:                            239772   AIC:                         1.954e+06
Df Residuals:                                239769   BIC:                         1.954e+06
Df Model:                                         2
Covariance Type:                          nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.8112      0.056    103.782      0.000       5.701       5.921
TGA_count     -1.5667      0.033    -46.994      0.000      -1.632      -1.501
PSI           -0.5796      0.001   -848.114      0.000      -0.581      -0.578
==============================================================================
Omnibus:                      115.922   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              129.156
Skew:                           0.001   Prob(JB):                     9.00e-29
Kurtosis:                       3.114   Cond. No.                         149.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.775
Model:                                          OLS   Adj. R-squared:                  0.775
Method:                               Least Squares   F-statistic:                 4.121e+05
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:24:18   Log-Likelihood:            -9.6616e+05
No. Observations:                            239772   AIC:                         1.932e+06
Df Residuals:                                239769   BIC:                         1.932e+06
Df Model:                                         2
Covariance Type:                          nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept           15.5162      0.083    186.495      0.000      15.353      15.679
stop_codon_count    -3.0540      0.019   -159.933      0.000      -3.091      -3.017
PSI                 -0.6208      0.001   -892.970      0.000      -0.622      -0.619
==============================================================================
Omnibus:                       73.151   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               78.257
Skew:                          -0.016   Prob(JB):                     1.02e-17
Kurtosis:                       3.082   Cond. No.                         226.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.263
Model:                                         OLS   Adj. R-squared:                  0.263
Method:                              Least Squares   F-statistic:                 4.270e+04
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:24:21   Log-Likelihood:            -1.0571e+06
No. Observations:                           239772   AIC:                         2.114e+06
Df Residuals:                               239769   BIC:                         2.114e+06
Df Model:                                        2
Covariance Type:                         nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     33.5796      0.098    341.194      0.000      33.387      33.773
TAA_count     -3.2473      0.039    -82.584      0.000      -3.324      -3.170
PSI           -0.2943      0.001   -291.867      0.000      -0.296      -0.292
==============================================================================
Omnibus:                    32872.005   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            65067.184
Skew:                           0.861   Prob(JB):                         0.00
Kurtosis:                       4.883   Cond. No.                         187.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.262
Model:                                         OLS   Adj. R-squared:                  0.262
Method:                              Least Squares   F-statistic:                 4.257e+04
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:24:24   Log-Likelihood:            -1.0572e+06
No. Observations:                           239772   AIC:                         2.114e+06
Df Residuals:                               239769   BIC:                         2.114e+06
Df Model:                                        2
Covariance Type:                         nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     32.3417      0.089    362.708      0.000      32.167      32.517
TAG_count     -4.0717      0.050    -81.317      0.000      -4.170      -3.974
PSI           -0.2899      0.001   -291.767      0.000      -0.292      -0.288
==============================================================================
Omnibus:                    33349.316   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            66609.113
Skew:                           0.868   Prob(JB):                         0.00
Kurtosis:                       4.911   Cond. No.                         174.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.243
Model:                                         OLS   Adj. R-squared:                  0.243
Method:                              Least Squares   F-statistic:                 3.840e+04
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:24:26   Log-Likelihood:            -1.0603e+06
No. Observations:                           239772   AIC:                         2.121e+06

## 8. Secondary Structure MFE (Minimum Free Energy) Analysis

In [25]:
# Discretize MFE
assay_data["liao2023"]["predicted_MFE_disc"] = plot_utils.mfe_discretize_variable(
    assay_data["liao2023"]["predicted_MFE"], 
    5, 
    min_val=-30, 
    max_val=-10, 
    labels=True,
    include_above_max=True,
    include_below_min=True,
)

In [26]:
bbox_to_anchors = {
    "liao2023" : (0.5, -0.55),
}
ceiling_counts = {
    "liao2023" : 8,
}
target_bins = {
    "liao2023" : 5,
}
figsizes = {
    "liao2023" : (2.8, 2.25),
}

for key in ["liao2023"]:
    for model_col, model_name in model_error_cols.items():
        fig = plot_utils.plot_grouped_violin_analysis(
            assay_data[key],
            predictor_col=model_col,
            target_col="PSI",
            group_col="predicted_MFE_disc",
            predictor_label=f"Model Error (Score - PSI)",
            target_label="Experimentally Measured PSI",
            group_label="Predicted Minimum Free Energy (kcal/mol) (↓ = More Stable)",
            target_bins=target_bins[key],
            ceiling_count=ceiling_counts[key],
            min_samples=20,
            title=f"{display_names[key]}, {model_name}",
            cmap='inferno',
            ylim=(-105, 105),
            legend=True,
            legend_loc="lower center",
            legend_ncols=8,
            bbox_to_anchor=bbox_to_anchors[key],
            dpi=600,
            figsize=figsizes[key],
            fontsize_title=8,
            fontsize_axis_labels=7,
            fontsize_xtick=7,
            fontsize_ytick=7,
            fontsize_legend=7,
            fontsize_sample_counts=5,
            numeric_binning=False,
            legend_row_major=True,
            group_orders=[
                '< -30',
                '(-30, -25]',
                '(-25, -20]',
                '(-20, -15]',
                '(-15, -10]',
                '-10+'
            ]
        )
        fig.show()
        fig.savefig(f"figures/{key}_{model_col}_MFE_Error.svg", bbox_inches='tight')
        plt.close()
                
        model = smf.ols(f"{model_col} ~ predicted_MFE + PSI", data=assay_data[key]).fit()
        print(key, model_name, model.summary())

liao2023 SpliceAI                             OLS Regression Results
==============================================================================
Dep. Variable:     spliceai_avg_error   R-squared:                       0.461
Model:                            OLS   Adj. R-squared:                  0.461
Method:                 Least Squares   F-statistic:                 1.025e+05
Date:                Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                        01:24:30   Log-Likelihood:            -1.0176e+06
No. Observations:              239772   AIC:                         2.035e+06
Df Residuals:                  239769   BIC:                         2.035e+06
Df Model:                           2
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         6.3562      0.119     53.555      0.000       6.124       6.589
predicted_MFE    -0.9383      0.007   -137.467      0.000      -0.952      -0.925
PSI              -0.3654      0.001   -447.424      0.000      -0.367      -0.364
==============================================================================
Omnibus:                     4358.187   Durbin-Watson:                   2.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9160.243
Skew:                           0.004   Prob(JB):                         0.00
Kurtosis:                       3.958   Cond. No.                         261.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 Pangolin                                    OLS Regression Results
============================================================================================
Dep. Variable:     pangolin_average_usage_avg_error   R-squared:                       0.760
Model:                                          OLS   Adj. R-squared:                  0.760
Method:                               Least Squares   F-statistic:                 3.802e+05
Date:                              Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                      01:24:32   Log-Likelihood:            -9.7358e+05
No. Observations:                            239772   AIC:                         1.947e+06
Df Residuals:                                239769   BIC:                         1.947e+06
Df Model:                                         2
Covariance Type:                          nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -3.6881      0.099    -37.342      0.000      -3.882      -3.494
predicted_MFE    -0.5580      0.006    -98.235      0.000      -0.569      -0.547
PSI              -0.5920      0.001   -871.226      0.000      -0.593      -0.591
==============================================================================
Omnibus:                      290.468   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              292.118
Skew:                          -0.083   Prob(JB):                     3.69e-64
Kurtosis:                       3.044   Cond. No.                         261.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
liao2023 AlphaGenome                                    OLS Regression Results
===========================================================================================
Dep. Variable:     alphagenome_junctions_psi_error   R-squared:                       0.285
Model:                                         OLS   Adj. R-squared:                  0.285
Method:                              Least Squares   F-statistic:                 4.773e+04
Date:                             Sat, 29 Nov 2025   Prob (F-statistic):               0.00
Time:                                     01:24:33   Log-Likelihood:            -1.0535e+06
No. Observations:                           239772   AIC:                         2.107e+06
Df Residuals:                               239769   BIC:                         2.107e+06
Df Model:                                        2
Covariance Type:                         nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        13.6277      0.138     98.880      0.000      13.358      13.898
predicted_MFE    -0.9523      0.008   -120.146      0.000      -0.968      -0.937
PSI              -0.2842      0.001   -299.677      0.000      -0.286      -0.282
==============================================================================
Omnibus:                    26035.399   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            46793.820
Skew:                           0.740   Prob(JB):                         0.00
Kurtosis:                       4.579   Cond. No.                         261.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.